# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Leaderboard CI

on:
  workflow_dispatch: # Bouton "Run workflow" dans GitHub
  schedule:
    - cron: '0 */2 * * *' # Exécution automatique toutes les 2 heures (pile)
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'
        
    - name: Installer les dépendances npm
      run: npm ci

    - name: Installer les navigateurs Playwright
      run: npx playwright install chromium --with-deps
      
    - name: Executer un script de test
      run: npm run hello

    - name: Exécuter Playwright
      run: npm run playwright:test

    - name: Commiter et pousser les résultats
      run: |
        git config --global user.name 'leaderboard[bot]'
        git config --global user.email 'leaderboard[bot]@users.noreply.github.com'
        git add dist/data/
        git commit -m "chore: mise à jour automatique des données" || exit 0
        git push